name: psi_pfl_py310
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.15
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - tqdm=4.66.5
  - pytorch
  - torchvision
  - nltk=3.9.1
  - pillow=10.4.0
  - protobuf=3.20.3
  - certifi=2025.1.31
  - pip
  - pip:
      - flwr==1.13.1
      - fedlab==1.3.0
      - fedartml==0.1.33
      - ray==2.10.0
      - tensorflow==2.17.0
      - folktables==0.0.12
